### ISSUE TITLE
Внешний вид окна запуска Wedpack App v1.0.0

### ISSUE THREAD

**Issue by aleta2020** [GyverLibs/Settings-discover#1]
Всем привет! После обновления библиотек (как написано на странице) все успешно запустилось. Но есть пожелания:
При запуске приложения или HTML получаем окно с IP и маской. Все правильно определилось и подсказка про настройки Chrome отработала, но не понятно, что делать дальше:
![image](https://github.com/user-attachments/assets/fd9f454f-2272-4208-9bf7-ef22e607c20f)
Непривычное расположение кнопки "Лупа" (хинта нет): сразу даже не понять, что это кнопка, а не иконка приложения (в GyverHub кнопки расположены справа) - если на ПК мышка меняет вид указателя, то на смартфоне и планшете этого нет.
Пожелание: как-то выделить "Лупу" (чтобы было понятно, что ее нужно нажать) и разместить по возможности вправо или текст при пустом списке написать типа: Проверьте маску и нажмите кнопку "Лупа" (Поиск).

**Comment by GyverLibs** [comment]
согласен, переделаю

**Comment by GyverLibs** [comment]
типо того
![image](https://github.com/user-attachments/assets/c68744bb-eb79-43ef-82d8-cc5691574b0f)
