### ISSUE TITLE
Сообщение Settings discover: Disable WEB RTC anonymizer: chrome://flags/#enable-webrtc-hide-local-ips-with-mdns

### ISSUE THREAD

**Issue by aleta2020** [GyverLibs/Settings-discover#2]
Доброго времени суток!
Видимо после каких-то обновлений на ПК Google Chrome (а может и Win10 (!)) при запуске index.html (поиск устройств) всплывает такое сообщение: "**Disable WEB RTC anonymizer: chrome://flags/#enable-webrtc-hide-local-ips-with-mdns**". В Chrome такого параметра нет. 
- версия файла html: Settings discover v1.0.1
- версия Chrome: Версия 131.0.6778.86 (Официальная сборка), (64 бит)

Скрипт и приложение скачаны со [страницы](https://github.com/GyverLibs/Settings-discover#settings-discover)
Ранее я просто браузером открывал index.html - все работало...
Приложение поиска на Android работает корректно. 
Устройства и браузер находятся в одной локальной сети.
Окно в браузере имеет такой вид:
![FireShot Capture 327 - Settings discover v1 0 1 - ](https://github.com/user-attachments/assets/5fcb2b0c-30dd-4396-b2d2-b169d8d44829)
При клике на кнопку ничего не происходит. А если обновить страницу - выскакивает окно про WEB RTC.
Как быть? Может я что-то сломал?

**Comment by GyverLibs** [comment]
привет, в браузере должна быть такая настройка и всё должно работать, не знаю в чём дело. Поиск работать не будет - вон IP error потому что, приложение не смогло определить свой ip

**Comment by aleta2020** [comment]
Проверил на другом ПК - там сборка хрома 129.0.6668.100
указанная настройка есть - там все отключается и скрипт работает.
Пока проверял - хром скачал обновление до 131. Перезапустил - настройка исчезла  :-) и скрипт выдает сообщение о WEB RTC.
Похоже, что гугл окончательно удалил эту настройку или куда-то спрятал...  :-(
Судя по сообщениям сообщества: такое у них уже было в 103 сборке...

**Comment by GyverLibs** [comment]
я обновил тоже - работает)

**Comment by aleta2020** [comment]
Шайтан какой-то...
Версия 131.0.6778.86 (Официальная сборка), (64 бит) под WIN10 ? С перезапуском?

**Comment by GyverLibs** [comment]
Версия 131.0.6778.86 (Официальная сборка), (64 бит) WIN11

**Comment by aleta2020** [comment]
Может дело в 10? У меня в списке флагов нужного `#enable-webrtc-hide-local-ips-with-mdns` нет...
Нашел пока решение: в ярлыке запуска хрома добавил параметр:
`--disable-features=WebRtcHideLocalIpsWithMdns`
Этот параметр не отключает флаг вообще, а только на время работы запущенного хрома.
Если потом запустить хром без параметра, то сообщение опять будет выскакивать.

**Comment by GyverLibs** [comment]
не знаю. В принципе можно сделать ручное задание локального ip

**Comment by aleta2020** [comment]
Накопал, как параметрами отключить флаг, если его нет в списке: нужно однократно запустить хром с параметрами:
`--flag-switches-begin --enable-features=WebRtcHideLocalIpsWithMdns --flag-switches-end`
После этого указание параметра в ярлыке не требуется!!!  :-)

**Comment by aleta2020** [comment]
> не знаю. В принципе можно сделать ручное задание локального ip

Но ручное задание IP не помешает :-)

**Comment by GyverLibs** [comment]
Зафурычило?

**Comment by aleta2020** [comment]
> Зафурычило?

Я понял, что это - проблема текущей сборки хрома в win10 и есть ее решение: как выключить флаг, когда его нет в настройках. В таком виде проблема не относится к Settings discover, хотя в будущем эту настройку могут вообще исключить (!), т.к. она влияет на безопасность браузера.
Но добавление ручного ввода IP в Settings discover наверняка пригодится для подобных случаев.
